CLUSTAL

EMBOSS_001      LAQEEEQKPEPRLSQKLAQVGTKLLKVPLMLAFLYLFVCSLDVLSSAFQL     50
EMBOSS_001      --------------------------------------------------      0

EMBOSS_001      AGGKVAGDIFKDNAILSNPVAGLVVGILVTVLVQSSSTSTSIIVSMVSSG    100
EMBOSS_001      --------PFEHNVVLGISMLAFIAVLWLTEALHVTVTAILVPVMAVFFG     42

EMBOSS_001      LLEVSSAIPIIMGSNIGTSVTNTIVALMQAGDRTDFRRAFAGATVHDCFN    150
EMBOSS_001      IFETQAAL---------NNFANSIIFLFLGG------FALAAAMHHQGLD     77

EMBOSS_001      WL---SVLVLL--PLEAATGYLHHVTGLVVASFN----------------    179
EMBOSS_001      KVIADKVLAMAQGKMSVAVFMLFGVTALLSMWISNTATAAMMLPLVLGVL    127

EMBOSS_001      --------------------------------------------------    179                                                                       
EMBOSS_001      SKVDADKQRSTYVFVLLGVAYSASIGGIATLVGSPPNAIAAAEVGLSFTD    177

EMBOSS_001      -------------------------------------------    179                                                                
EMBOSS_001      WMKFGLPTAMMMLPMAIAILYFLLKPAPVNWDKGKVVTLGIFG    220
